flowchart TD
    subgraph "Capa de Presentación"
        UI[Interfaz de Usuario
        Compose Multiplatform + Kobweb]
    end
    
    subgraph "Capa de Lógica de Negocio"
        VM[ViewModel
        Kotlin Multiplatform]
    end
    
    subgraph "Capa de Datos"
        M[Modelo
        Entidades y Repositorios]
        DB[(MongoDB)]
    end
    
    UI <--> VM
    VM <--> M
    M <--> DB
    
    classDef presentation fill:#f9d5e5,stroke:#333,stroke-width:1px;
    classDef business fill:#eeac99,stroke:#333,stroke-width:1px;
    classDef data fill:#e6d7b9,stroke:#333,stroke-width:1px;
    classDef database fill:#b6dcfe,stroke:#333,stroke-width:1px;
    
    class UI presentation;
    class VM business;
    class M data;
    class DB database;
